__author__ = 'Manfred Minimair <manfred@minimair.org>'


class DefaultNames:
    default_file = 'kernel-chc.json'  # default file name for connection file
    storage_key = 'chc'  # prefix to identify items corresponding to this application in Storage
    config_file = 'jupyter_chconsole_config.py'
    # name of the configuration file generated by chconsole
    # located in the jupyter_core.paths.jupyter_config_dir() directory
