import os


__author__ = 'Manfred Minimair <manfred@minimair.org>'


class DefaultNames:
    default_file = 'kernel-chc.json'  # default file name for connection file
    storage_key = 'chc'
    # prefix to identify items corresponding to this application in Storage
    config_file = 'jupyter_chconsole_config.py'
    # name of the configuration file generated by chconsole
    # located in the jupyter_core.paths.jupyter_config_dir() directory
    #
    # chrun:
    chrun_config_file = 'jupyter_chrun_config.py'
    kernel_user = 'ch_kernel'
    data_key = 'ch_tunnel'
    # key for storing data in addition to connection file keys

    # to remove
    # host = 'ses.chgate.net'  # host to run kernel sessions; configurable
    #
    # still in remote_connector.py
    # gate = 'in.chgate.net'  # ssh server that can see host; configurable
    # gate_user = 'chconnect'  # ssh user name; configurable
    #
    # gate_pem = os.path.normcase(
    #     '/home/ec2-user/chrun_data/chconnect.pem')  # configurable
    # private ssh key for ssh user
    # local_conn_dir = os.path.normpath('/var/www/html')  # configurable
    # path to the local location of the connection file
    # remote_conn_dir = '~'
    # path to the remote location of the connection file
    # configurable
